steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - functions
      - deploy
      - --trigger-http # HTTP trigger
      - --runtime=python37
      - --entry-point=api # Defined function in main.py
      - api # Cloud Function name
